##############################################################
#                                                            #
#                                                            #
#                     Coded by n1zamu!                       #
#                                                            #
#                                                            #
##############################################################


messages:
  successfullyMessage: "&aКапча успешно пройдена. Приятной игры!" # Текст при успешном прохождении капчи
  kickMessage: "&cВы не прошли капчу!" # Текст при неверном прохождении капчи

# Плэйсхолдер %number% - ответ чтобы пройти капчу
# Плэйсхолдер %timeLeft% - оставшееся время для ответа

bossBarName: " &f(Осталось %timeLeft% секунд)"
anvilName: "&7Введите число %number%" # Название меню капчи
time: 60 # Время на решение капчи
notification: # Оповещение об успешном прохождении капчи

  sound: true # Звук при оповещении игрока
  soundType: "ENTITY_EXPERIENCE_ORB_PICKUP" # Тип звука при оповещении

  message: true # В виде сообщения в чат
  title: false # В виде сообщения на весь экран